Update RabbitMQ with SBOM attestations
docker-library/official-images pull request #15474
Opened 2023-10-04 04:34 UTC by whalelines

Provide attestations for software built within the Docker build context.

2023-10-04 12:54 UTC, LaurentGoderre submitted a review, later dismissed

2023-10-05 22:40 UTC, yosifkit approved these changes
Accepting as experimental extra SBOM information. I'd love to have something that is less "manual". Ideally container SBOM scanners could automatically discover these non-os packages possibly through a combination of Dockerfile and container filesystem analysis.

2023-10-05 22:50 UTC, yosifkit requested changes

2023-10-05 22:50 UTC, yosifkit commented on library/rabbitmq
> +GitCommit: b2387a802850aa877b8feefdd679e12536072db9
These should be pointing at https://github.com/docker-library/rabbitmq/commit/6e5870068747ebef1d00134c52bd9a8e41cb2b4b as that is what `generate-stackbrew-library.sh` will end up with.

2023-10-06 00:19 UTC, yosifkit approved these changes

2023-10-06 00:22 UTC, yosifkit commented
Repushed to match the `library/rabbitmq` file to the output of `generate-stackbrew-library.sh` from https://github.com/docker-library/rabbitmq/.

2023-10-06 00:38 UTC, merged