Update postgres alpine SBOM attestions
docker-library/official-images pull request #15476
Opened 2023-10-04 18:06 UTC by whalelines

2023-10-04 19:15 UTC, LaurentGoderre submitted a review, later dismissed

2023-10-05 22:41 UTC, yosifkit approved these changes
Accepting as experimental extra SBOM information. I'd love to have something that is less "manual". Ideally container SBOM scanners could automatically discover these non-os packages possibly through a combination of Dockerfile and container filesystem analysis.

2023-10-05 22:52 UTC, yosifkit requested changes

2023-10-05 22:52 UTC, yosifkit commented on library/postgres
> +GitCommit: 2bff0ce33b76f03f4e6986497e0ab084dad10e9d
Similar to https://github.com/docker-library/official-images/pull/15474#pullrequestreview-1660880825, these should be https://github.com/docker-library/postgres/commit/6f4ae836406b010948f01fbcb400a31dca4fdf52

2023-10-06 00:23 UTC, yosifkit approved these changes

2023-10-06 00:23 UTC, yosifkit commented
Repushed to match the `library/postgres` file to the output of `generate-stackbrew-library.sh` from https://github.com/docker-library/postgres/.

2023-10-06 00:38 UTC, merged